
class Model_TextConverter:
    def decodeAsciiCharacter(character):
        switch = {
            0x40 : ' ',         # convert '@' to ' '
            0x20 : '.',         # convert ' ' to '.'
            0x2E : '-',         # convert '.' tp '-'
            0x5C : '\'',        # convert '\\' to '\''
            0x0D : "\n",
        }
        return switch.get(character, chr(character))
    
    def decodeMessageCharacter(character):
        switch = {
            0x0D : '?',
            0x0E : '\'',
            0x20 : '0',
            0x21 : '1',
            0x22 : '2',
            0x23 : '3',
            0x24 : '4',
            0x25 : '5',
            0x26 : '6',
            0x27 : '7',
            0x28 : '8',
            0x29 : '9',
            0x2A : '.',
            0x2B : ',',
            0x2D : '\"',
            0x2E : '\"',
            0x2F : ':',
            0x40 : 'A',
            0x41 : 'B',
            0x42 : 'C',
            0x43 : 'D',
            0x44 : 'E',
            0x45 : 'F',
            0x46 : 'G',
            0x47 : 'H',
            0x48 : 'I',
            0x49 : 'J',
            0x4A : 'K',
            0x4B : 'L',
            0x4C : 'M',
            0x4D : 'N',
            0x4E : '0',
            0x4F : '!',
            0x60 : 'P',
            0x61 : 'Q',
            0x62 : 'R',
            0x63 : 'S',
            0x64 : 'T',
            0x65 : 'U',
            0x66 : 'V',
            0x67 : 'W',
            0x68 : 'X',
            0x69 : 'Y',
            0x6A : 'Z',
            0x6D : '-',
            0x6E : '(',
            0x6F : ')',
            0x80 : 'a',
            0x81 : 'b',
            0x82 : 'c',
            0x83 : 'd',
            0x84 : 'e',
            0x85 : 'f',
            0x86 : 'g',
            0x87 : 'h',
            0x88 : 'i',
            0x89 : 'j',
            0x8A : 'k',
            0x8B : 'l',
            0x8C : 'm',
            0x8D : 'n',
            0x8E : 'o',
            0xA0 : 'p',
            0xA1 : 'q',
            0xA2 : 'r',
            0xA3 : 's',
            0xA4 : 't',
            0xA5 : 'u',
            0xA6 : 'v',
            0xA7 : 'w',
            0xA8 : 'x',
            0xA9 : 'y',
            0xAA : 'z',
            0xAC : ' ',
            0xC6 : "[v]",
            0xCB : '\n'
        }
        return switch.get(character, chr(character))